springdoc:
  # 禁用原本的 swagger-ui 页面
  swagger-ui:
    enabled: false
  # 开启 openapi 数据接口（Scalar 需要读取这个）
  api-docs:
    enabled: true
    path: /v3/api-docs


spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liWW6wErqTVejoub
            client-secret: 60942fc6380f22a3ff8eca6b5814f1375101680d
            redirect-uri: "{baseUrl}/login/oauth2/code/github"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/langchain4j?currentSchema=service&stringtype=unspecified
    username: xlqs
    password: xlqsnhyq521..
  data:
    redis:
      host: xlqs.com
      port: 6379
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
    qdrant:
      host: xlqs.com
      port: 6334 # gRPC 默认端口是 6334，HTTP 默认是 6333
      api-key: Xlqsnhyq521.. # 如果配置了权限校验，没有则留空

# MyBatis-Plus 相关配置
mybatis-plus:
  type-aliases-package: com.example.dto
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    # 开启驼峰命名自动映射（如数据库 user_name 映射到 Java 的 userName）
    map-underscore-to-camel-case: true
    # 打印 SQL 日志（开发阶段强烈推荐，方便排错）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 告诉 MP，主键是用 PostgreSQL 的自增（即我们设置的 IDENTITY）
      id-type: auto

ai:
  rag:
    enabled: false

jwt:
  secret: xlqs-Fv6fmMFTQiop0_C9L-lGXyF6OiurOulb5bd63nXWMAQ
  skip: true

langchain4j:
  open-ai:
    chat-model:
      base-url: https://ark.cn-beijing.volces.com/api/coding/v3
      api-key: ${API-KEY}
#      model-name: ark-code-latest
      model-name: deepseek-v3.2
      log-requests: true
#      log-responses: true
    streaming-chat-model:
      base-url: https://ark.cn-beijing.volces.com/api/coding/v3
      api-key: ${API-KEY}
      model-name: ark-code-latest
      log-requests: true
#      log-responses: true
    embedding-model:
      base-url: https://ark.cn-beijing.volces.com/api/coding/v3
      api-key: ${API-KEY}
      model-name: doubao-embedding-vision
      log-requests: true
      dimensions: 1024
#      log-responses: true
#
server:
  ssl:
    enabled: true
    key-store: classpath:certs/xlqs.p12
    key-store-type: PKCS12
    key-store-password: Xlqsnhyq521..
  port: 8080

